name: linters

on:
  pull_request:
    paths-ignore:
      - 'resource/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'resource/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MAX_LINE_LENGTH: 120

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: python -m pip install flake8
      - name: flake8
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: flake8
          run: flake8 --max-line-length ${{env.MAX_LINE_LENGTH}} genshin tests

  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: python -m pip install isort
      - name: isort
        uses: liskin/gh-problem-matcher-wrap@v1
        with:
          linters: isort
          run: isort --check-only --diff genshin tests

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: black
        uses: psf/black@stable
        with:
          options: "--line-length ${{env.MAX_LINE_LENGTH}}"
          src: "genshin tests"