# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    
    - name: Cache Python packages
      id: cache-pip
      uses: actions/cache@v2
      env:
        cache-name: cache-python-${{ steps.setup-python.outputs.python-version }}
      if: startsWith(runner.os, 'Windows')
      with:
        path: ~\AppData\Local\pip\Cache
        # 使用依赖文件hash值创建缓存key
        key: ${{ runner.os }}-pip-${{ env.cache-name }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
            ${{ runner.os }}-pip-${{ env.cache-name }}-
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

    - name: Install dependencies
      run: |
        pip install pytest pytest-cov .
        pip install -r requirements.txt
    
    - name: Test with pytest
      run: |
        pytest --cov=genshin
