# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python test

on:
  push:
    branches:
      - main
    paths:
      - 'genshin/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'genshin/**'
      - 'tests/**'

permissions:
  contents: read

jobs:
  pytest:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install pytest pytest-cov -e .
        python -m pip install -r requirements.txt
    
    - name: Test with pytest
      uses: liskin/gh-problem-matcher-wrap@v1
      with:
        linters: pytest
        run: pytest --cov=genshin
